CREATE USER odoo7 WITH PASSWORD 'odoo7'  CREATEDB;
CREATE USER odoo8 WITH PASSWORD 'odoo8'  CREATEDB;
CREATE USER odoo9 WITH PASSWORD 'odoo9'  CREATEDB;
CREATE USER odoo10 WITH PASSWORD 'odoo10'  CREATEDB;
CREATE USER odoo11 WITH PASSWORD 'odoo11'  CREATEDB;

CREATE USER intoodoo7 WITH PASSWORD 'intoodoo7'  CREATEDB;
CREATE USER intoodoo8 WITH PASSWORD 'intoodoo8'  CREATEDB;
CREATE USER intoodoo9 WITH PASSWORD 'intoodoo9'  CREATEDB;
CREATE USER intoodoo10 WITH PASSWORD 'intoodoo10'  CREATEDB;
CREATE USER intoodoo11 WITH PASSWORD 'intoodoo11'  CREATEDB;
